version: '3'
services:
  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: pss
    ports:
      - 27017:27017
    volumes:
      - ./db/mongo/mongo_data:/data/db
      - ./db/mongo/init/:/docker-entrypoint-initdb.d/
  app:
    build: .
    environment:
      MONGO_DATABASE: pss
      MONGO_USER: user
      MONGO_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    links:
      - mongo
    tty: true
