version: '3'
services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: pss
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./db/mysql_data:/var/lib/mysql
  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db/mongo_data
      - ./configdb:/data/configdb
  app:
    build: .
    environment:
      MYSQL_DATABASE: pss
      MYSQL_ROOT_PASSWORD: password
      MYSQL_HOST: mysql
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    links:
      - mysql
    tty: true
